<?php

namespace AppBundle\Repository;

/**
 * TeaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeaRepository extends \Doctrine\ORM\EntityRepository
{
}
